### ISSUE TITLE
Discriminated union

### ISSUE THREAD

**Issue by adriangb** [wyfo/apischema#220]
https://github.com/samuelcolvin/pydantic/pull/2336

If it is possible already, could a clear example be added to the docs, and if not, would it be possible to make this work? Thanks!

**Comment by wyfo** [comment]
I've a not so old [branch](https://github.com/wyfo/apischema/tree/discriminator) in which I've implemented OpenAPI *discriminator* feature, but I've never finished it. In fact, I was not clear about the interface I wanted to have. 
For now, I've implemented 3 different ways of add discriminator :
- an annotation for unions to be used with `typing.Annotated`: https://github.com/wyfo/apischema/blob/discriminator/examples/union_discriminator.py
- a decorator for a base class to be inherited: https://github.com/wyfo/apischema/blob/discriminator/examples/inherited_discriminator.py (which adds the discriminator in the parent schema as proposed in OpenAPI documentation)
- a field metadata to annotate an object field: https://github.com/wyfo/apischema/blob/discriminator/examples/field_discriminator.py

But I think I need to rework this a little bit. For example, I want to handle discrimination of classes without field to store the discriminator (so it has to be excluded from deserialized data and put back by serialization). So, work is in progress, but I admit it's not my priority for the moment (I'm working hard on performance at this right moment, with big things coming). If your need is important, I can reconsider it. Also, don't hesitate if you have some ideas, or feedbacks about the linked examples.

In the OpenAPI *discriminator* feature, there are two aspects: one about schema (for example, `discriminator` part is used by several tools, especially in UI), and the other about deserialization optimization. (Of course, *apischema* implementation covers both). Unfortunately, if your need is about performance, I think there is no simple way of doing it for now.

Something like this would work:
```python
from dataclasses import dataclass
from timeit import timeit
from typing import Any, Literal, Mapping, get_args, get_origin, get_type_hints

from apischema import ValidationError, deserialize, deserializer


class Base:
    _discriminator = "type"
    _discriminator_mapping: dict[str, type["Base"]] = {}

    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)
        field_type = get_type_hints(cls)[Base._discriminator]
        if get_origin(field_type) == Literal:
            assert all(isinstance(val, str) for val in get_args(field_type))
            Base._discriminator_mapping.update(
                (val, cls) for val in get_args(field_type)
            )
        else:
            Base._discriminator_mapping[cls.__name__] = cls


@deserializer
def discriminate(data: Mapping[str, Any]) -> Base:
    if Base._discriminator not in data:
        error = "missing property"
    elif data[Base._discriminator] not in Base._discriminator_mapping:
        error = f"invalid discriminator, expected {list[Base._discriminator_mapping]}"
    else:
        # /!\ Calling apischema.deserialize in a deserializer is a very bad practice /!\
        # There is no current way to retrieve deserialization parameter, e.g. aliaser
        # used in first deserialize call.
        # The advised way is to use a ContextVar if needed.
        return deserialize(Base._discriminator_mapping[data[Base._discriminator]], data)
    # Yes, it's not easy to manually raise ValidationError for now, I have to work on it
    raise ValidationError(children={Base._discriminator: ValidationError([error])})
```
However, it requires a base class and it uses `deserialize` inside a deserializer.

**Comment by adriangb** [comment]
Very cool, I'm amazed at how much you've experimented already.

And you're spot on in saying that there's 2 aspect to a discriminator:
1. Performance -> purely a backend / implementation concern
2. Documentation -> purely a tooling concern

For what it's worth, amongst those implementations, I _generally_ prefer 2 or 3 (i.e. not `Annotated`). I think they are more flexible and easier to read.

I wonder if, from a deserialization standpoint, it would be worth thinking of the "use a field to discriminate a model" as a special case of "use an arbitrary function w/ the signature `def discriminator(serialized_obj: Any) -> Optional[DiscrimatedType]` to short circuit Union logic". That way, the door is open for other situations where users may want to short circuit an expensive Union evaluate that are not compliant w/ the OpenAPI concept of a discriminator (e.g. using 2 properties together as a key into a mapping of types). Then for the particular case of an OpenAPI discriminator, there could be a special function / object that provides both the schema metadata and an implementation of a discriminator function.

**Comment by wyfo** [comment]
> I wonder if, from a deserialization standpoint, it would be worth thinking of the "use a field to discriminate a model" as a special case of "use an arbitrary function w/ the signature `def discriminator(serialized_obj: Any) -> Optional[DiscrimatedType]` to short circuit Union logic". That way, the door is open for other situations where users may want to short circuit an expensive Union evaluate that are not compliant w/ the OpenAPI concept of a discriminator (e.g. using 2 properties together as a key into a mapping of types). Then for the particular case of an OpenAPI discriminator, there could be a special function / object that provides both the schema metadata and an implementation of a discriminator function.

I didn't try to push further this reflexion, as I've finally only implemented OpenAPI discriminator. Maybe open a separate issue when the need arises.
