### ISSUE TITLE
Installation fails on Mac M1

### ISSUE THREAD

**Issue by AnderUstarroz** [wyfo/apischema#492]
Installation fails on new Mac with M1 chips throwing the following error:
```
    from apischema.serialization import serialize
  File "/Users/my_user/.pyenv/versions/3.9.9/envs/cubist-games-manager/lib/python3.9/site-packages/apischema/serialization/__init__.py", line 34, in <module>
    from apischema.serialization.methods import (
ImportError: dlopen(/Users/my_user/.pyenv/versions/3.9.9/envs/cubist-games-manager/lib/python3.9/site-packages/apischema/serialization/methods.cpython-39-darwin.so, 0x0002): tried: '/Users/my_user/.pyenv/versions/3.9.9/envs/cubist-games-manager/lib/python3.9/site-packages/apischema/serialization/methods.cpython-39-darwin.so' 
(mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```

**Comment by mbutnaruy** [comment]
uninstall the library (`pip uninstall apischema`) then install it using arch arm64 `arch -arm64 pip install apischema`

**Comment by lkk7** [comment]
@wyfo This issue seems to be long gone, feel free to close this.

**Comment by mkramb** [comment]
@AnderUstarroz how did you fix the issue? thanks

**Comment by lkk7** [comment]
@mkramb I have no problems on M1. 

Looks like your case is an indirect import through a few other packages. Could this be a part of your problem? Not sure.
Are you able to pip install apischema and just test importing it directly? It works instantly for me.

If it does work, then doing `pip cache purge` and reinstalling might solve it. I've also read that `arch -arm64 pip install <whatever>` might help.
